[package]
name = "wasmparser"
version = "0.51.2"
authors = ["Yury Delendik <ydelendik@mozilla.com>"]
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmparser.rs"
keywords = ["parser", "WebAssembly", "wasm"]
description = """
A simple event-driven library for parsing WebAssembly binary files.
"""
exclude = ["fuzz/**/*", "tests/**/*", "testsuite/**/*"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"
wast = "7.0.0"

[badges]
travis-ci = { repository = "bytecodealliance/wasmparser.rs" }

[features]
# The "deterministic" feature supports only Wasm code with "deterministic" execution
# across any hardware. This feature is very critical for many Blockchain infrastructures
# that rely on deterministic executions of smart contracts across different hardwares.
deterministic = []

[[bench]]
name = "benchmark"
harness = false
