[package]
name = "wasmparser"
version = "0.17.3"
authors = ["Yury Delendik <ydelendik@mozilla.com>"]
license = "Apache-2.0"
repository = "https://github.com/yurydelendik/wasmparser.rs"
keywords = ["parser", "WebAssembly", "wasm"]
description = """
A simple event-driven library for parsing WebAssembly binary files.
"""
exclude = ["fuzz/**/*", "tests/**/*"]

[dependencies]

[dependencies.hashmap_core]
version = "0.1.1"
optional = true

[badges]
travis-ci = { repository = "yurydelendik/wasmparser.rs" }

[features]
# The "std" feature enables use of libstd. The "core" feature enables use
# of some minimal std-like replacement libraries. At least one of these two
# features needs to be enabled.
default = ["std"]
std = []
core = ["hashmap_core"]
