[package]
name = "wasmparser"
version = "0.10.0"
authors = ["Yury Delendik <ydelendik@mozilla.com>"]
license = "Apache-2.0"
repository = "https://github.com/yurydelendik/wasmparser.rs"
keywords = ["parser", "WebAssembly", "wasm"]
description = """
A simple event-driven library for parsing WebAssembly binary files.
"""
exclude = ["fuzz/"]

[dependencies]

[badges]
travis-ci = { repository = "yurydelendik/wasmparser.rs" }
