[package]
name = "wasmparser"
version = "0.35.3"
authors = ["Yury Delendik <ydelendik@mozilla.com>"]
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/yurydelendik/wasmparser.rs"
keywords = ["parser", "WebAssembly", "wasm"]
description = """
A simple event-driven library for parsing WebAssembly binary files.
"""
exclude = ["fuzz/**/*", "tests/**/*", "testsuite/**/*"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"
wabt = "0.9.1"

[dependencies.hashbrown]
version = "0.5.0"
optional = true

[badges]
travis-ci = { repository = "yurydelendik/wasmparser.rs" }

[features]
# The "std" feature enables use of libstd. The "core" feature enables use
# of some minimal std-like replacement libraries. At least one of these two
# features needs to be enabled.
default = ["std"]
std = []
core = ["hashbrown"]

[[bench]]
name = "benchmark"
harness = false
