[package]
name = "wasmparser-fuzz"
version = "0.0.1"
authors = ["Yury Delendik <ydelendik@mozilla.com>"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies.wasmparser]
path = ".."

[dependencies.libfuzzer-sys]
git = "https://github.com/rust-fuzz/libfuzzer-sys.git"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"

[[bin]]
name = "validate"
path = "fuzz_targets/validate.rs"
